### PR TITLE
Install git package in the base image

### PR DESCRIPTION
**Pull request by tamizhgeek**
Please review..

and also, the base image download is taking a huge time - can you please do that release.sh part?

### CODE REVIEW

**Comment by tamizhgeek** [comment]
@ashwanthkumar comments?

**Comment by ashwanthkumar** [comment]
@tamizhgeek The base image download is a one time operation right? Wouldn't that happen automatically as part of the build.sh? VBox downloads it right?

**Comment by tamizhgeek** [comment]
@ashwanthkumar yes, yesterday even that one time operation was crawling for me.

**Comment by ashwanthkumar** [comment]
@tamizhgeek That's one time download of 250+M :) Do you have other suggestions on reducing the time?

**Comment by tamizhgeek** [comment]
@ashwanthkumar Nothing other than blaming our poor internet speed at office. Probably a go pipeline with release as a manual stage? 

Not related to this, but my mac hard disk is actually full. How do you guys manage this with lot of virtual box images lying around?

**Comment by ashwanthkumar** [comment]
I periodically remove all boxes using `vagrant box list | xargs -I% vagrant box remote %` and re-run the changes. Also the VMDK files are dynamically expanding so each image holds only ~1-1.5G of storage actually :) 

Also I never do a full `kitchen converge && kitchen verify`. I only run the tests for my cookbooks. That also helps. I'm planning to setup a machine at our office which would do the entire kitchen test nightly everyday.

**Pull request merged**
